### ISSUE TITLE
Feedback: Page Navigation Enhancements

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#107]
The navigation interface of pages has been improved, including a back button and page count.  Please leave feedback and suggestions below.

[![Page Navigation](http://img.youtube.com/vi/_F5QBLt_iEU/0.jpg)](http://www.youtube.com/watch?v=_F5QBLt_iEU)

**Comment by tedrick** [comment]
Nakul

**Comment by gibbonsbr** [comment]
This feature worked really well and will be so helpful for longer forms. I really like that the user has the option to tab through the pages or to enter a specific page directly. One thing that might help for pages with long forms would be to have a table of contents window that would have the list of the group names for each page to make it easier for the user to quickly navigate to the correct page.  I also really liked that questions that were not assigned to a group in a field-list appear at the bottom of each page. This will be extremely helpful for images or comment fields that may be needed at different stages of completing the form which had previously required the user to scroll to find in the form. However, form authors should take note to clarify the question names to distinguish the questions that are specific to a page from those that appear on each page.

It was a bit unexpected that the submit button only appeared on the last page of the form, since users may tab to other pages to verify information before submitting. If a group that defines a page has relevant restrictions on it, the page will still display but the questions are removed. It would be nice if pages could be skipped if the group that defines them is not relevant.

**Comment by nakulb** [comment]
The paging feature works as expected. With a large number of pages, if you are clicking on the next button fast on the app, instead of grey-ing out at the end, it goes into the submit mode. 

I tested by copying and pasting fields in excel from a different form and that threw pagination off. If became one large form page and acted more like in page links:
![image](https://user-images.githubusercontent.com/3268459/36871907-7b6d7268-1d58-11e8-8444-0e3a69d8259b.png)
![image](https://user-images.githubusercontent.com/3268459/36872025-d630941e-1d58-11e8-9032-047236e90700.png)

The pagination does not work the same in the browser as it does in the App

**Comment by RITI8169** [comment]
In case where groups are created, I see that any other fields entered in the survey that are not part of any group repeat in all the pages created irrespective of their position in the excel sheet.

![grouppgsapp1](https://user-images.githubusercontent.com/31448327/37543909-6838405a-2920-11e8-9071-83b26fde551b.JPG)

![grouppgsapp2](https://user-images.githubusercontent.com/31448327/37543920-6cea7c44-2920-11e8-8352-026feca156f5.JPG)

**Comment by BrandonArmstrong** [comment]
@RITI8169 

As discussed, this is expected, as you have not defined which page the content is supposed to belong to.  Once choosing pages as a style, you must define what page the content will be a part of.  Another option is to include a relevant statement with the question.
