### ISSUE TITLE
BUG: Sign in view becomes unavailable when affected by network changes

### ISSUE THREAD

**Issue by paul-gpsit** [tedrick/Survey123-Testing#145]
**Application:** Field App 

**Device:**  iPhone 6

**Operating System:** iOS 11

**Error Description:** 
My phone was bouncing between wifi and 4G while I was attempting to sign in. The web view was greyed out and a busy indicator spinning, but the sign in page never actually loaded.

**How to reproduce:**
I was 'signed in' when sitting in the office (as I had just downloaded a survey). I walked outside. I started a survey and tried to send it. The app then told me I wasn't signed in and the sign in view attempted to load but never did.
I tried exiting the survey and then tried reaching the sign in view from the main "Sign In" link, but same thing, even after I specifically turned wifi OFF on my phone. I finally had to force close the app and re-open it and was then able to sign in.

**Comment by phil-wilson** [comment]
This issue was encountered due to the Esri-Guest Wifi network being accessible from outside the building with very weak signal, which causes network issues if device remains connected as move further way. The device will remain connected to Wifi but not have enough signal to load the internet and login page. Moving further away from office and/or switching to 4G will resolve this issue and the login will work as expected.

**Comment by paul-gpsit** [comment]
Phillip - note that just moving further away and/or switching to 4G didn't resolve the issue. I actually turned wifi off and went back to the app and still couldn't get to the log in screen. It only worked once I force closed and re-opened the app.
