### ISSUE TITLE
FEEDBACK: Variable replacement for labels and hints 

### ISSUE THREAD

**Issue by BrandonArmstrong** [tedrick/Survey123-Testing#164]
Labels and hints in your survey can now display the contents of another question by referring to the question name in the text using the format ${field_name}.  Refer to the documentation for more information.

This should be designed in Survey123 Connect and then verified using the Field App, and the Web App.

http://docdev.arcgis.com/en/survey123/desktop/create-surveys/xlsformnotes.htm#ESRI_SECTION1_17679FA12F7645B8B94577920C2219D2

**Comment by tedrick** [comment]
Sarah Bubka

**Comment by sbubka94** [comment]
Are calculations expected to work in the Labels or Hints? I tried a simple calculation for the hint and the label but it's showing me the concatenated values rather than using the operation I indicate. I tried specifying int() as well but no luck.

[Holistic Oct 2018.xlsx](https://github.com/tedrick/Survey123-Testing/files/2447533/Holistic.Oct.2018.xlsx)
