### ISSUE TITLE
CHALLENGE: On-premises installation

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#17]
**Context:** While the Survey123 website can be configured to work with an ArcGIS Enterprise implementation, many customers still have need for an onsite installation of the Survey123 website & form processing API.

**Challenge:** The Survey123 team is proposing providing the website as a _container,_ which is a relatively new method for providing standardized setups of software by creating  self-contained virtual machine.  There are two methods of installing this:
1. An installation script and content is posted at the Early Adopter Community.  Instructions for installing are here: 
[Survey123 on premises installation.docx](https://github.com/tedrick/Survey123-Testing/files/1257789/Survey123.on.premises.installation.docx)

2. A pre-built box is available at https://esri.box.com/v/Survey123Box-v1

The installation currently requires
- [Vagrant](https://vagrantup.com)
- [VirtualBox](https://virtualbox.org)

Please attempt to install the Survey123 website.  Upon successful installation, it will be available at `http://<installation machine>:8080 `

**Comment by tedrick** [comment]
Alex, Christian

**Comment by JohnHasthorpe** [comment]
2.4 testing complete

**Comment by LisaEdman** [comment]
Hi, 
I have looked into this and I end up with a few questions. My organisation cannot use internet connection at all during installation because of security reasons.

In the word dokument attached it says:
"For most customers, we intend to ship a completed installation; at this phase, we are providing the files to install the website" When will these be availiable?

Is there anyway to get these files right now due to our problem with no internet. We are currently looking at a Survey solution and if we cannot figure this out with on premise we will unfortunately choose a different survey solution.

Br, 
Lisa

**Comment by tedrick** [comment]
@LisaEdman - Based on early feedback, we are looking to revisit the on-premises installation strategy away from containers, so this is no longer applicable.

**Comment by selrahc83** [comment]
Hi,
Where can i found the installation files describe in the document Survey123 on premises installation.docx?

**Comment by tedrick** [comment]
@selrahc83 - This path for on-premises installation was stopped last year after initial feedback.  We are working on another on premises installation solution and will update the [Esri Early Adopter Community](https://bit.ly/S123beta) when ready.
