### ISSUE TITLE
FEEDBACK: Feature Report performance in multiple browsers

### ISSUE THREAD

**Issue by BrandonArmstrong** [tedrick/Survey123-Testing#172]
The Feature Report capability is available in the majority of web browsers.

In testing out Feature Reports, please try to test the performance and review the results using the following web browsers.  List any differences that are noticed.

* Internet Explorer 11
* Microsoft Edge
* Chrome
* Firefox
* Safari

Some suggested steps may include...
*  Download the default template for a survey and add it to the list of selectable templates
* Generate a report for a single record (select a single record)
* Generate Batch Report including multiple records (select multiple records)

Optional: Modify the default template to include expressions that can be used to aid in formatting that can be applied to your Word doc.

Reference Documentation here: https://doc.arcgis.com/en/survey123/browser/analyze-results/featurereporttemplates.htm

**Comment by Temmermand** [comment]
**Application:** Website 

**Device:** Desktop - HOLISTIC57 

**Operating System:** Windows 10 Enterprise, Version 1803

**Browser:** Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

Issue: hitting back on the browser instead of "X" on the Report (Beta) to go back results in a grey box blocking access the underlying website.

Repro steps: 
1. Press Manage templates link.
2. Press back on the browser.
3. Try to click on the page. Grey layer is blocking access to page.
4. Requires page refresh to access page.

![image](https://user-images.githubusercontent.com/38793244/51343767-f8c46280-1a4b-11e9-8690-d222302e37da.png)

![image](https://user-images.githubusercontent.com/38793244/51343813-185b8b00-1a4c-11e9-8935-ab2bb8d719db.png)

**Comment by Temmermand** [comment]
After I upload my new template, I was uncertain that I needed to click the close button to move forward.

![image](https://user-images.githubusercontent.com/38793244/51345319-7f2e7380-1a4f-11e9-9d66-bef0294700a2.png)

**Comment by Temmermand** [comment]
After I select a template, it is unclear that I need to enable "Save result to your account" before I can type an item title.

![image](https://user-images.githubusercontent.com/38793244/51347871-22828700-1a56-11e9-8d61-ec397ac18f68.png)

![image](https://user-images.githubusercontent.com/38793244/51347925-3d54fb80-1a56-11e9-98b6-e2ccb4a13675.png)

**Comment by Temmermand** [comment]
Chrome, FF, and IE have different behavior from Edge when "Manage templates" > "Upload a template" > "Choose file".

The first three work well. They default to my last location (desktop) and look for appropriate file types. Edge looks in documents and shows all file types, which makes it confusing to find the template.

Chrome:
![image](https://user-images.githubusercontent.com/38793244/51349313-d1749200-1a59-11e9-8343-82976b07fa74.png)

IE:
![image](https://user-images.githubusercontent.com/38793244/51349334-e3563500-1a59-11e9-8a50-cf50a8fc2b27.png)

Firefox:
![image](https://user-images.githubusercontent.com/38793244/51349351-f49f4180-1a59-11e9-8e7e-70645e5b3ec5.png)

Edge:
![image](https://user-images.githubusercontent.com/38793244/51349371-0b459880-1a5a-11e9-93be-8ec73ec1f185.png)

**Comment by BrandonArmstrong** [comment]
Moved some issues into General UI Feedback doc which can be brought up for discussion
