### ISSUE TITLE
"No" is considered a stop word to exclude in word cloud by default

### ISSUE THREAD

**Issue by RachelGEsri** [tedrick/Survey123-Testing#219]
**Application:** Website

**Device:** PC

**Operating System:** Windows 10

**Browser:** Chrome

**Error Description:** "No" is filtered out when the "Exclude stop words (currently only available in English)" is turned on. This seems like it may be an important word to continue seeing. May want to reconsider this one?

**How to reproduce:** See Analyze tab in completed survey

**Have you tested with another survey?** No

**Comment by zhif7782** [comment]
Hi @RachelGEsri ,
Thanks for your feedback.

From our research, "yes" and "no" are listed in most stop words list for Enligh on the internet and also the one we are using, that's why they are excluded by default. I've added your feedback to the issue that [allows users to include/exclude custom words from the stop words list](https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3230) in our backlog.
