### ISSUE TITLE
FEEDBACK: View data in related tables

### ISSUE THREAD

**Issue by oopsliu** [tedrick/Survey123-Testing#231]
With version 3.5 of Survey123 website we have added the ability to view and interact with related tables in the **Data** page. This means that you can see and filter information in a repeat. When interacting with related tables, you can decide which mode you want to use: only see records in current table, see related records in current repeat, or see all repeats in the response.

![image](https://user-images.githubusercontent.com/7564300/59018140-c9d25000-8877-11e9-9fb8-05970c1ecc8c.png)

**Please create a survey with at least one repeat using Survey123 Connect, submit at least two responses, and test against the Data page of Survey123 website.**

Please comment with your observations / feedback.

**Comment by morganwaterman** [comment]
What is the expected behavior with image repeats? I set up an image repeat and I am expecting to see 2 photos in this table:
![image_repeat](https://user-images.githubusercontent.com/51456665/59069595-86beaf80-886c-11e9-8226-ce83fa152156.PNG)
If image repeat related tables are not going to display any data, they should not be available. 
Survey link: https://arcg.is/0aumSu

**Comment by oopsliu** [comment]
@morganwaterman Thanks a lot for the feedback, we have logged internal issue: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3619
to handle this.
