### ISSUE TITLE
FEEDBACK: Linked Content (link survey to other content in AGOL Organization)

### ISSUE THREAD

**Issue by BrandonArmstrong** [tedrick/Survey123-Testing#247]
## Linked Content

To better manage and organise your basemaps, web maps and offline map packages, we have introduced a new feature in Connect on the Settings tab of a survey called _Linked Content_.

Linked Content allows you to search your ArcGIS organization for basemaps, web maps, offline map packages and offline web map areas and associate them with your survey. By selecting a supported map type and adding it to you survey, users can view the linked online basemaps and web maps in the basemap chooser in the field app, and if the linked map was an offline package, they can download the package via the "Download map" menu on the device.

**To add linked content, you need to be signed in and your survey needs to have been published. You do not need to re-publish your survey after adding linked content, it will be automatically added provided you are online and signed in.**

![image](https://user-images.githubusercontent.com/6314443/64287194-eda73f80-cf13-11e9-85a6-c2b7d6e66f3a.png)

To make it easier to search all your supported maps types, a handy filter has been added to the Linked Content → Add Map Link search menu to help narrow down the results.

![filter_maps](https://user-images.githubusercontent.com/6314443/64287378-5db5c580-cf14-11e9-9448-27d5921f915b.png)

Please try to link various types of content to a survey prior to publishing and leave us some regarding your experience!

**Comment by fandrade86** [comment]
The linked content is not displayed immediately as soon as it linked. I had close the survey123 app on my cell phone (Android) and reopen it so it can be displayed.

![InboxCouldNotSeeLinkedContent](https://user-images.githubusercontent.com/21234095/64449375-92508b00-d094-11e9-8476-03a76e594af6.png)

**Comment by fandrade86** [comment]
It is great how labels are displayed on the linked content. 

![Screenshot_20190906-110050](https://user-images.githubusercontent.com/21234095/64449950-dd1ed280-d095-11e9-85d8-7e9aef4e4afa.png)

**Comment by BHSpendl** [comment]
I like the linked content, I definitely think our team will be using this in the future! 

**Feedback:** I had started a survey without changing the setting in my app at first and when I went back to change that map setting, I had to restart the app for it to take effect

**Enhancement Request:** It would be nice if there was a way for us as a company, when we push the app from the app store to our mobile device management platform that pushes things to the mobile devices, to configure things so that the Map type in the user's Survey123 app is automatically changed to Standard (or Advanced or whatever you end of naming it). Right now as the technology stands we will have to have each user set the Map settings in their app, close and re-open the app so that that setting is applied, and then proceed onward. For many people who are not technology savvy, it is already a difficult stumbling block to have to log in to our enterprise portal by going to settings and adding a portal, so adding in this step in our start up instructions is likely going to continue to increase the difficulty some people experience when setting up Survey123 on their device for the first time.

**Comment by sbubka94** [comment]
I think the link for actually adding content should say "Add Content Link" or "Add Item Link" because "Add Map Link" makes you think you can only like Web Maps here. 
![image](https://user-images.githubusercontent.com/22916127/64452113-8b2c7b80-d09a-11e9-9df4-46c2b6ba53b8.png)

**Comment by BHSpendl** [comment]
Hmm my linked content seems to have disappeared from the basemap options. Still trying to figure out why...It was working, then my iPad went to sleep while I was typing the review above and when I tried again I didn't see it.
I tried to create a new survey....and I got the pull data "created_by_fc is null" error that my team has been experiencing about 15% of the time.
Oh, it looks like it signed out again without telling me. *Note this was on ESRI Guest WIFI and not LTE like I previously experience that problem on. This seems to go back to the same base issues my team has been experiencing with submitting surveys using our vpn (spinning circle and pull data error), where connection is somehow lost (either WIFI or cellular connection), causing vpn credentials to be dropped, and Survey123 does not recognize that.
Now, when I tried to submit the survey that did not have the pull data error, it gave me the option to sign in so in one sense Survey123 did recognize that I was not signed in anymore. But it did not recognize it when creating the survey or opening the question option to move the geopoint.

**Comment by sbubka94** [comment]
If I download a map for offline use, is there a way to see that item on the device and delete it? For example, if I accidentally download an offline map but don't need it at the moment so I want to clear up storage on my phone.

I tried going to Settings > Map > Map Library, but I don't see my list of downloaded maps here. 

I'm told if I delete the survey entirely, that will get rid of the associated offline map, but this may be inconvenient for users who need other data associated with the survey.

I think it could be extremely beneficial if there was a place (like the map library) where you could view and manage (delete/update) all maps on the device for all surveys.

**Comment by DerekLaw** [comment]
In Survey123 Connect, when I link a web map in my AGOL org to the survey - I can select it from the map gallery button: 

![3](https://user-images.githubusercontent.com/1037228/64452971-56212880-d09c-11e9-9363-e3fea2f76a8a.png)

but the map does not appear in the preview in Connect, it shows up as grey:

![4](https://user-images.githubusercontent.com/1037228/64452980-5cafa000-d09c-11e9-8b26-efcab173ac73.png)

but it worked, because I can see it in the mobile app:

![5](https://user-images.githubusercontent.com/1037228/64452985-620cea80-d09c-11e9-9cc6-62ca66ff0079.png)

but it does not work in the web form:

![6](https://user-images.githubusercontent.com/1037228/64452988-66d19e80-d09c-11e9-998b-ad6f16f8cbcd.png)

I am expecting the selected linked web map to show up in the preview in Connect, and it should appear in the web form, no?

**Comment by Zachary-Sutherby** [comment]
When a Geotrace or Geoshape question types are nested in a repeat and the map parameter is specified in the body::esri:style column. The web map does not display in Survey123 Connect when previewing the survey. It displays perfectly fine in the field app, just not the preview in Survey123 Connect.

The behavior is not reproducible with Geopoint questions types in repeats, only Geotrace and Geoshape.

![S123ConnectWM1](https://user-images.githubusercontent.com/54078266/64453695-02174380-d09e-11e9-82a6-ddcf9c988ee9.JPG)

![S123ConnectWM2](https://user-images.githubusercontent.com/54078266/64453698-05aaca80-d09e-11e9-98ec-7e3f1fb35019.JPG)

**Comment by NeilMYoung** [comment]
On my iOS device (iphone 8, running iOS 12.4) using build 3.6.143, when trying to switch the basemap to one of the offline linked content maps that had been downloaded, the app crashed -  poof. gone. 
Not necessarily Survey123 issue, but I had to resign in as well when I relaunched the app. Because we use MFA on enterprise domain accounts, this was a bit of a pain to have to re-login to the app on the mobile device so if the user is going to get logged out each time it crashes, that could get a bit frustrating for our users.

**Comment by NeilMYoung** [comment]
Just a user experience comment - I found that having the linked content to be below the standard basemaps, was a bit confusing. From an end user perspective if I had content that my administrator had intently linked to the form, that basemap should be the first one on the list, not buried on the bottom of the list.

**Comment by NeilMYoung** [comment]
Just a user experience comment - I found that having the linked content to be below the standard basemaps, was a bit confusing. From an end user perspective if I had content that my GIS team had intently linked to the form, that basemap should be the first one on the list, not buried on the bottom of the list.

**Comment by BHSpendl** [comment]
When attempting to link to a vector tile service, I did not see it appear, but I am not sure whether it was related to my vpn issues or not. I could link to a vector tile package though. I think it would be worth it for someone to look into it though and verify that vector tile services can be linked (when vpns are not acting up)

**Comment by BrandonArmstrong** [comment]
@NeilMYoung in https://github.com/tedrick/Survey123-Testing/issues/247#issuecomment-528998278 you mentioned that you would like the linked content to show at the top of the list, above the standard basemaps as opposed to the bottom.  We are working on the ability to disable the Esri standard basemaps, so that they would not be in the list at all.  Would this equally satisfy the desire? 

Also, there is always the ability to set the default basemap from Connect or for each individual geo* question in the form.

**Comment by RahulFernando** [comment]
I linked map to my survey using survey123 connect but I cannot see my map in field app.
