### ISSUE TITLE
Undo Button Not Visible After Drawing Sketch

### ISSUE THREAD

**Issue by rothde** [tedrick/Survey123-Testing#261]
**Application:** Survey123 Connect 3.6.132, Survey123 Mobile App 3.6.143

**Device:**Connect --> Windows, Survey123 Mobile App --> Android

**Operating System:**

**Browser:** NA

**Error Description:** Undo button disappears when using the 'free draw' to create a line or polygon. The undo button is there before you draw the feature, but after you have drawn it the undo button disappears.

**How to reproduce:**
1. Open survey that contains line or polygon features
2. Click the map to open it and draw the feature
3. Click the 'free draw' tool (do not draw anything yet) - the undo button appears in the bottom right
4. Draw your feature - the undo button disappears so you now have no way to undo the drawing besides re-clicking either of the drawing tools to bring up the 'Confirm Area Sketch' dialog

**Have you tested with another survey?**  Yes

**Comment by brettstokes** [comment]
@rothde this behaviour is expected. At this stage of the workflow (prior to confirming your geometry capture), there is nothing to undo. If you confirm your geometry then re-sketch, you will have the option to undo:

![LineUndo](https://user-images.githubusercontent.com/46305628/64503661-4bba9500-d30f-11e9-9ca8-d0956c860aa8.gif)

The issue is that the undo button should be hidden until there is something in the undo stack. I have logged this issue - thanks.

**Comment by rothde** [comment]
Sorry, I must have miscommunicated the issue. The undo button disappears after you draw. As soon as you complete the drawing, the only option is to accept the drawing…there is no longer an option to undo it. The undo button only appears before you create the drawing when there is nothing to undo.

This behavior is visible in the attached video.

Please let me know if you have additional questions.

Deborah
