### ISSUE TITLE
Time zone for survey status

### ISSUE THREAD

**Issue by cdarti** [tedrick/Survey123-Testing#282]
**Application:** On Premises

**Browser:**Chrome

**Error Description:** 
In the Collaborate window, the user can set the open/close date base on -07:00 time zone.
Maybe this could be adjusted for the onpremise setting to make more sense.

![image](https://user-images.githubusercontent.com/12465858/67050845-6215f680-f0ee-11e9-9a4d-32cca3622b64.png)

**Comment by zhif7782** [comment]
Hi @cdarti , would you mind sharing more details with what the issue you encounter in the on-premises version?

**Comment by cdarti** [comment]
Not really an issue. But since the server is now on premises, maybe you can improve the UI and offers different choices for the time zone beside -7?

**Comment by brettstokes** [comment]
@cdarti this isn't a setting, it just shows your current timezone for clarity. If you're not in Pacific Daylight Time and saw this (-7:00 time zone) during the holistics session, it may have been due to the VM that was used? 

I am in Melbourne, Australia which is currently GMT+11:

![image](https://user-images.githubusercontent.com/46305628/67996437-5ce6a900-fca3-11e9-94a1-ed6fb476e2bb.png)
