### ISSUE TITLE
FEEDBACK: New Map Widget

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#301]
With the next release of Survey123, the website's `Geopoint` widget is being replaced with a `Map` widget, which will allow you to specify point, line or polygon collection.  

Please provide feedback on working with the map control.  Aside from simply adding a map to the form, also try revising the map control at different points in the authoring process.

**Comment by BrandonArmstrong** [comment]
Corey
Jerry
Josh
Kylie
Erica

**Comment by czielinski-esri** [comment]
The map question does not display in the field app.

This issue is seen on:

- iOS
- Windows

**Comment by czielinski-esri** [comment]
Opening the survey's hosted feature layer attribute table in ArcGIS Online shows that features have been submitted, but the geometries from the survey are not displaying in the map.

**Comment by kyliedonia** [comment]
It would be nice to support vertex or sketching to draw. I was able to tell what the options mean when adding the map to a survey in the browser, but I don't think it would be clear to users what they are picking there. (I didn't read any doc about this new question type though, so this mostly just says it doesn't seem too intuitive.)

**Comment by mappinista** [comment]
My survey used the dual-polygon map widget set to dual-polygon types of drawing. When I first opened the analyze tab, the geometries showed in the "Map" view and the legend was populated, but after I changed the basemap and scrolled down and back up, the geometries and legend items were gone.
![MappingWidgetBlankAnalyze](https://user-images.githubusercontent.com/14221059/73479972-3560b480-4356-11ea-82db-225faa772ea5.JPG)

**Comment by mappinista** [comment]
Also, the map in the survey opens with the drawing control on, which means you have to click the X to drag the map.  This was not intuitive, as I expected to have to drag the map, then activate the control.

**Comment by rbernstein80** [comment]
I opened my survey and have not edited the "geopoint" and it has been convert to a map. However now the is no map within my survey, it will only collect the lat, long from my phone. There is no map, so I am unable to enter a specific address. 
![map_Geopoint screenshot](https://user-images.githubusercontent.com/60482641/73480733-7a8de200-4368-11ea-90a3-0f6cabfe97dd.jpeg)
![Map_Geopoint screenshot](https://user-images.githubusercontent.com/60482641/73480734-7b267880-4368-11ea-9d1a-bdbbfffc784c.PNG)

**Comment by kyliedonia** [comment]
I added the new map to a new survey in the browser (Edge on the lab machine). Part way through configuring it, I clicked the "Collaborate" tab. I got the message about the survey being a draft and that I needed to publish it first. So I went back to the Design tab, and clicked on the map question section, but the "Edit" panel is empty and I can't finish configuring it.

I refreshed the web page in case it was the lab machine being weird, and now I can edit that component. I tried the same tab switching again, and again get the blank panel. So it seems like more than just the lab machine (Brandon said they can be weird).

I also tried in Chrome on my own laptop, and I do see this same behavior on changing tabs and then coming back to designer.

(Jerry is seeing similar for the multiple choice question type - the edit panel was blank after reopening the survey in the browser to make an update)

**Comment by kyliedonia** [comment]
As someone who forgets that the mouse is over the map in design mode and scrolls and messes up her initial extent and scale, it would be great if there was a way to "lock" the map in the edit panel once you have it set where you want so that you can no longer change the extent or scale until you "unlock" it.

**Comment by cwhit45** [comment]
> The map question does not display in the field app.
> 
> This issue is seen on:
> 
> * iOS
> * Windows

I am having the same issue with the map not showing up in the field app.

**Comment by JTHerman** [comment]
Would it be possible/useful for users to be able to see previously-submitted geometries in geopoint/map questions? Referring to the challenge scenario, this would reduce the number of redundant submissions.

If this were to become a feature, I would also like to see some sort of snapping functionality.

**Comment by DerekLaw** [comment]
Create a new survey with the map widget question type, published. I was also not able to view in new location type question in the survey. Using Google Pixel 2, Android v10 OS.

**Comment by kyliedonia** [comment]
I'm not able to use the question in the field app (iPhone 7 with iOS 13.3, and a new survey with the map question with polygon with the sketch tools -- it shows a broken map looking icon).

**Comment by kimberly-peter** [comment]
Also did not see map in field app. iPad Air 12.3.1.

**Comment by kyliedonia** [comment]
The extent and scale shown in the map is different in the Edit tab, preview of the survey, and once published. I know with different size boxes it is hard to have them all exactly the same, but at least the preview and the published should match. I *think* I'd expect the extent from the Edit tab to be honored in the preview and published survey.

Here is what I see now in the Edit tab: 
![image](https://user-images.githubusercontent.com/3945570/73498145-44a12b80-4371-11ea-8a57-46e323fb5db4.png)

Here it is in the web designer preview:
![image](https://user-images.githubusercontent.com/3945570/73498158-54207480-4371-11ea-8dfe-9785281596bd.png)

And here is the same in the published survey:
![image](https://user-images.githubusercontent.com/3945570/73498185-67cbdb00-4371-11ea-9ac8-c07c6889e2de.png)

**Comment by kyliedonia** [comment]
It would be great if the survey author could set a default drawing shape. I'm not a fan of the "corrected" shapes for data collection (outside sketching of rough areas) so that as a default doesn't work for me, and I feel users are likely to use the default or not understand they can change it (or won't want to capture twice once they realize what the default is).

**Comment by kyliedonia** [comment]
When filling out the survey, the home button should take you to the authored scale and extent. Right now I think it is using the org's default extent.

**Comment by loganbwu** [comment]
> Create a new survey with the map widget question type, published. I was also not able to view in new location type question in the survey in the Survey123 mobile app v3.9. Using Google Pixel 2, Android v10 OS.
> 
> I also tested with the Survey123 mobile app (earlier release v3.7) on iOS and got the same behavior - since this is an earlier release of the app, my expectation is that I would get some sort of warning b'c the new question type is not supported, no?
> 
> I was able to open, view and submit a survey with the map widget via the web form in Chrome, FireFox, Edge, and Safari without issue.

Screenshots of Android below. Examples of polygon (vertex) and point maps.

![Screenshot_20200131-111556_Survey123](https://user-images.githubusercontent.com/23466039/73502090-fac14f80-441b-11ea-800c-2b6856571113.jpg)
![Screenshot_20200131-111608_Survey123](https://user-images.githubusercontent.com/23466039/73502091-fb59e600-441b-11ea-996e-247b1858b503.jpg)

**Comment by loganbwu** [comment]
Bug
Platform: Web browser response form
Description: Drawing a self-intersecting polygon with the mouse is allowed and can be submitted. The saved geometry (in AGOL or Data view) appears to be a single (first?) part of an intermediate multipart polygon.

**Comment by zhif7782** [comment]
Hi @czielinski-esri , for https://github.com/tedrick/Survey123-Testing/issues/301#issuecomment-580389268, would you mind sharing some detailed steps to reproduce the issue? 
* Did you submit the survey from the field app where the map does not show up? If yes, this is caused by the map cannot work in the field app currently, we will fix this in the next beta release.
* If you submitted the survey from the web app (in a browser), please share some steps which can reproduce the issue. I tried the vertex and sketch tools for a polyline, both geometries show as expected in ArcGIS Online and the Survey123 website.

**Comment by zhif7782** [comment]
Hi @kyliedonia , thanks for the feedback. For https://github.com/tedrick/Survey123-Testing/issues/301#issuecomment-580395190,

> It would be nice to support vertex or sketching to draw instead of having to pick one. I was able to tell what the options mean when adding the map to a survey in the browser, but I don't think it would be clear to users what they are picking there. (I didn't read any doc about this new question type though, so this mostly just says it doesn't seem too intuitive.)

Did you mean to allow the vertex and sketch drawing tools to end-users at the same time so they can choose either one to use?

**Comment by zhif7782** [comment]
Hi @JTHerman , thanks for the feedback. For https://github.com/tedrick/Survey123-Testing/issues/301#issuecomment-580406285, 

> Would it be possible/useful for users to be able to see previously-submitted geometries in geopoint/map questions? Referring to the challenge scenario, this would reduce the number of redundant submissions.
> 
> If this were to become a feature, I would also like to see some sort of snapping functionality.

By design, the web app and the field app (new Standard map mode) both load an existing web map set by the survey author as the "basemap" for the Map question (geopoint/geotrace/geoshape). Hence, you can first create a web map in ArcGIS Online to include the hosted feature layer of the survey itself (or a hosted feature layer view of it), then set this web map as the map for the question, all end-users would be able to see submitted geometries to the survey then.

Also logged "snapping" requirement in our backlog.

**Comment by zhif7782** [comment]
Thank you ALL for the feedbak. Following items are logged in our backlog:

* Map question cannot work in the field app (cannot show the map control).
* Do not active the (freehand) drawing tool by default, otherwise, you cannot move the map first.
* Provide an intuitive way for deleting the drawn geometry.
* Smart shapes is hard to use.
* Edit panel is blank when switching from the Collaborate tab to the Design tab.
* Edit panel: the set home extent is easy to mess up with scrolling the mouse in the panel.
* Map extents are not identical in the Edit panel, left preview panel, published web app.
* Data: when clicking a polygon on the map, some times the map zooms to an extent which is smaller than the polygon's envelope.
* Data: use the "basemap" set in the survey's geo question as the default map.
* Draw a self-intersecting polygon (bow-tie shape) and submit, the result geometry only contains the first part of the polygon.

**Comment by kyliedonia** [comment]
> Hi @kyliedonia , thanks for the feedback.
> 
> 1. For [#301 (comment)](https://github.com/tedrick/Survey123-Testing/issues/301#issuecomment-580395190),
> 
> > It would be nice to support vertex or sketching to draw instead of having to pick one. I was able to tell what the options mean when adding the map to a survey in the browser, but I don't think it would be clear to users what they are picking there. (I didn't read any doc about this new question type though, so this mostly just says it doesn't seem too intuitive.)
> 
> Did you mean to allow the vertex and sketch drawing tools to end-users at the same time so they can choose either one to use?

Yes -- It seems some projects or people might want to use one or the other, or not care which the user picked, and it seems an odd constraint. For example, if I want to have kids sketch an area they like on a map, I don't care which way they do it. However, both would have to be easy to use, and I could see the confusion that might just be passing to the person filling out the survey...

> 1. For [#301 (comment)](https://github.com/tedrick/Survey123-Testing/issues/301#issuecomment-580503348),
> 
> > It would be great if the survey author could set a default drawing mode/tool. I'm not a fan of the "corrected" shapes for data collection (outside sketching of rough areas) so that as a default doesn't work for me, and I feel users are likely to use the default or not understand they can change it (or won't want to capture twice once they realize what the default is).
> 
> Did you mean when using the "sketch" drawing tool, instead of the "smart shapes" mode, you would like to split the circle, triangle, rectangle shapes as different tools/modes so end-users will be clear for what they are going to draw?

No, I meant that the "smart shapes" tool shouldn't be the default when doing sketch drawing. Or that you should be able to pick while authoring which one is the default (or even exclude one or the other).

> 
> 1. For [#301 (comment)](https://github.com/tedrick/Survey123-Testing/issues/301#issuecomment-580505583),
> 
> > When filling out the survey, the home button should take you to the authored scale and extent. Right now I think it is using the org's default extent.
> 
> By design, the home button in the web app will take you to the home/initial extent set by the survey author, I think this is the same as you expected. For this case, did you set a similar initial extent to the org's default extent and then encountered the "extents are not identical among Edit panel, preview panel and the published web app" issue? If not, would you mind sharing some steps to reproduce the issue?

OK I definitely found that the home button took me to, for example, the extent of the world, when the survey was authored focused on the location of a particular elementary school. 

Here's what I did, and I've shared the survey publicly ("Parks for Issue 301" - https://arcg.is/0TqSSm):
1. Create a new survey using the web designer.
2. Add a singleline text option with label "Park name"
3. Add a map to the survey. To set the location, search for "Prestwood elementary Sonoma" -- zoom in a bit so that, in the designer, the track fills the map.
    --> Notice at this point that the track doesn't fill the map in the preview of the survey, but only in the map shown in the Edit panel. The two tracks (Edit panel and preview) are the same size on the screen, but the map in the preview is bigger than the one in the Edit panel, so there is more shown around it. I don't think the home button experience I had was related to seeing different extents in Edit, preview, and published.
    ![image](https://user-images.githubusercontent.com/3945570/73688807-addeb280-4681-11ea-8afc-da6804cb7310.png)
4. Save and publish the survey. 
5. Open the survey to fill it out. 
    --> When you open the survey to fill it out, the track is even smaller than it was on preview. I haven't even touched the home button yet.
    ![image](https://user-images.githubusercontent.com/3945570/73688969-0b72ff00-4682-11ea-9573-5985f61a334c.png)
6. Press "Home" on the map. You see the world extent.
    ![image](https://user-images.githubusercontent.com/3945570/73689022-28a7cd80-4682-11ea-8814-4bb47cbf65b2.png)

> 
> 1. For [#301 (comment)](https://github.com/tedrick/Survey123-Testing/issues/301#issuecomment-580505583),
> 
> > When editing the shape after drawing it, it seems more likely that I want to change a vertex or two than that I want the same shape resized or rescaled.
> 
> Currently, by design, you can only edit vertex of the geometry if it's drawn by the vertex drawing tool (high accuracy purpose). If the geometry is drawn by a smart shape tool or a freehand tool, you cannot edit any vertice but only the ratio and size. Would you mind sharing any use case for the necessity of editing vertex of a shape (triangle, circle, rectangle...)?

Ahh ok. I sketched something, it wasn't quite right, and I couldn't change the one error in the shape. I had to start over. It would have been nice to be able to edit the shape as I was making a rough outline of an area.

**Comment by tedrick** [comment]
Thanks all for feedback.  Closing out issue.
