### ISSUE TITLE
Download Connect/Field App from the Windows Store

### ISSUE THREAD

**Issue by IsmaelInRedlands** [tedrick/Survey123-Testing#308]
**Test:** Download Connect and/or Field app from the Windows Store links provided during holistic testing Jan 2020 Redlands.

**Comments:**

* Did people succeed downloading?:
    * Erica: OK
    * William: OK
    * Leonard: OK
    * Kylie: Not OK. Logged in from Holistic54 logged in as htlab
    * Kanchana: Not OK.
    * Kim: Not OK

* Kylie: The Explorer team has had many issues in the past offering Explorerfrom the Store. For unknown reasons, users could not download the app. This is a machine per machine issue.  They have seen instances where a user could download the app OK and then suddenly after an update they could not download anymore.  They have also seen that some logged in users can downloads but others not.  Justin Colville has become the resident expert on Microsoft Store issues.

**Comment by kunjoo91** [comment]
Unable to download Survey123 Connect from Microsoft Store. Tried with logins to personal, work and no login. It keeps adding it to the wishlist.

![image](https://user-images.githubusercontent.com/24254822/73475931-28d46000-4346-11ea-8adb-c6a1b60bf772.png)

**Comment by czielinski-esri** [comment]
Unable to download through Microsoft Store on Holistic59

**Comment by rbernstein80** [comment]
Unable to download through the Microsoft Store on my personal work laptop. I was not able to click the "get" button.

**Comment by kyliedonia** [comment]
Once I signed in to the MS Store, I could click the "Get" button. Then the install button was grayed out -- turns out the install was requiring Windows 10 version 17763 or greater, and the lab machines are 17134.

I downloaded the setup from the beta, and then I get a wizard start screen with no buttons:

![blankWizard](https://user-images.githubusercontent.com/3945570/73477422-0f80e300-4349-11ea-88f1-90170e6f0afb.png)

**Comment by kyliedonia** [comment]
Here is some info/tips from the Explorer Beta: https://community.esri.com/groups/explorer-beta/blog/2019/07/01/sideloading-explorer-for-arcgis

**Comment by kimberly-peter** [comment]
I see the [same thing as Kylie](https://github.com/tedrick/Survey123-Testing/issues/308#issuecomment-580383528) with the .exe from the Early Adopter site.

**Comment by someevil** [comment]
Unable to download anything before signing in, this is not ideal, but I understand this may be group policy/Windows store option.

Able to download Survey123 for ArcGIS 3.9.124B

Tried to download Connect (31/01/2020) and it fails, recording made here:
https://i.imgur.com/wR1nNbs.gif

Reverted to downloading direct from Early Adapter site.

**Comment by marikavertzonis** [comment]
From Melbourne Holistic
 - Ben - mixed results see above https://github.com/tedrick/Survey123-Testing/issues/308#issuecomment-580517025
- John - company policy prohibits the tiny url, but link from EAC did. successfully see the items in the store.
- Logan & Andrew - company IT policy prohibits access to the store

**Comment by phil-wilson** [comment]
Thanks everyone on feedback about installing from MS store. It appears some issues are related to versions of Windows on test machines, other are graphics drivers related with installer, and other issues preventing install could be caused by group policy or IT restrictions for the MS store. Once the apps are live in MS Store, and not hidden by private direct link, further testing should be completed.

**Comment by tedrick** [comment]
re-opening for Olympia holistic
