### ISSUE TITLE
Feedback: Update Survey Notifications in the Survey123 field app

### ISSUE THREAD

**Issue by IsmaelInRedlands** [tedrick/Survey123-Testing#323]
**Context:** With version 3.9 we want to accommodate this [GeoNet Idea](https://community.esri.com/ideas/13677-notify-users-a-survey123-form-has-been-updated).  Give the GeoNet Idea a quick read and let us know if 3.9 fits the mark.

**Comment by BrandonArmstrong** [comment]
Allison
Francisco
Leonard

**Comment by lbarnhill** [comment]
In previous testing, a newly updated survey had a red dot on the icon indicating that survey needed updating.  The new release has a new line of text stating a survey has been updated.  The user can easily miss this single line of text and will not know the form to be updated. Upon clicking the changed survey, the user is prompted to update or continue.  Should there be additional text advising the user to submit pending surveys before updating?

**Comment by lbarnhill** [comment]
In addition, if the user does not completely close Survey123 on the iPad, there is no notification of update.

**Comment by fandrade86** [comment]
Updates alerts work great to advise the user of the updated Survey123 form.

The popup received when you select the survey form is also great because it allows the user to update the survey from there which makes the process more user friendly.

It would be great to see something similar for the inbox. An alert would work great to advise the user that the inbox needs to be refreshed.
