### ISSUE TITLE
FEEDBACK: Multiple Photos & Files (web)

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#366]
With 3.10, Survey123 now supports collecting multiple photos or files in one question.  In the Survey123 web designer, you can set either a fixed number to collect or set a minimum/maximum number.

Author forms with the web designer and fill in forms in the web.

Known limitations:
- the fixed number, minimum and maximum has not yet been implemented in the Survey123 field app

![authorMultiple 2020-06-03 11_38_04](https://user-images.githubusercontent.com/1319289/83676962-53525600-a590-11ea-8ea4-592082fed800.gif)
![CaptureMultiple](https://user-images.githubusercontent.com/1319289/83676981-5a796400-a590-11ea-9382-d26f3aedff34.gif)

**Comment by Shwujeng** [comment]
Holistic lab session on 6/4/2020 Redlands:
- [ ] Bobby Horne
- [ ] Chris Ferner
- [ ] Kylie Donia
- [ ] Matthew Baber
- [ ] Matthew Woodlief
- [ ] Mike Cox
- [ ] Red Cylwik

**Comment by fandrade86** [comment]
Feedback:

Wording does not sound correct. Question states "Number of files required:"

Unless the image question(s) is set as required, the image question is not required. 

![image](https://user-images.githubusercontent.com/21234095/83792844-80663d80-a650-11ea-96ca-7f7395e0632e.png)

**Comment by fandrade86** [comment]
Testing Results:

Works great and I can't wait for this option to be available also on Connect (Not sure if it is already).

I can see using it for different work types and requiring users to take more than 1 picture. I am not sure how it will work with features in our SDE environment but really looking forward to it.
Screenshot of attempting to submit with 1 required picture missing:

![image](https://user-images.githubusercontent.com/21234095/83793305-3762b900-a651-11ea-8695-b97faa06010e.png)

Screenshot of just with one picture since 1 to 2 pictures were needed in the question.

![image](https://user-images.githubusercontent.com/21234095/83793415-5bbe9580-a651-11ea-81ff-ef0e49211f83.png)

**Comment by jerjer007** [comment]
Two scenarios were tested: 1) with a requirement of 4 images; and 2) with a range of 1 to 5.  Both worked as expected. In both scenarios, photos were taken.  I liked that there was an option to retake a photo. Editing the photos (deleting, renaming) also worked as expected.

**Comment by lbarnhill** [comment]
Seems to work as expected.  Great opportunity for the user to replace a poor image as well as record several images.  A great time saver in survey design.  

Suggestion?  Can you require the user to change the image name if more than one image is taken?

**Comment by Zachary-Sutherby** [comment]
Everything worked as expected in testing, I tested in on a browser using both my desktop and Chrome on my IOS device and the minimum and the maximum number of photos were respected. 

No issues with submission all attachments were uploaded as expected. I tested using the Web Form URL parameters but because I was using ArcGIS Enterprise 10.8 I was not seeing the attachments come through which is expected. When I have a chance to spin up a 10.8.1 environment I will retest to see what the behavior is there. 

One thing I did notice when trying to see if there is a cap to the maximum number of images I can specify, I tried specifying 250 or 600 to see if it will take it and the designer set a cap to 20. 

When I tried setting 150 the designer still set a cap to 20 but in the form I saw that the max was set to 150 so I was not sure what the actual max is. 

I have a gif of the behavior located on \\sutherby1\MobileTaskforce\06_04_Survey123Holistic

![SurveyImage2](https://user-images.githubusercontent.com/54078266/83794411-d50ab800-a652-11ea-8221-fb7d2c8fc67b.JPG)

When I publish the survey the 150 is maintained: 

![SurveyImage](https://user-images.githubusercontent.com/54078266/83794441-de942000-a652-11ea-81e4-c45dad781051.JPG)

**Comment by kyliedonia** [comment]
Testing: 
- specified image count
- min or max, or both set
- both with required and not required questions

Found:
1. The field names given by default are now "field_2" "field_3" etc. If I create a survey with an image question in the released web designer the default field name is better, based on the label.

    --> Here is an image from the beta:
    ![image](https://user-images.githubusercontent.com/3945570/83796196-785ccc80-a655-11ea-8556-568406e6721d.png)

    --> Here is an image from the released site:
    ![image](https://user-images.githubusercontent.com/3945570/83796123-5bc09480-a655-11ea-9503-282836f58ebc.png)

**Comment by Zachary-Sutherby** [comment]
I know in 3.10 Connect the ability to specify only upload images or only take photos using the device's camera is anticipated, is this functionality expected for the Web Designer as well?

**Comment by tedrick** [comment]
@sueeg asks is there a way to migrate existing surveys with images in repeat sections to a multiple photos

**Comment by tedrick** [comment]
Thanks all for the feedback,

Based on the feedback, we are looking at how to properly message the limits in the web designer in allowing multiple photos.  We will also consider how to provide guidance for migrating survey designs that used previous workarounds.
