### ISSUE TITLE
[FEEDBACK] - Creating Survey from existing feature service in Connect.

### ISSUE THREAD

**Issue by Shwujeng** [tedrick/Survey123-Testing#389]
With 3.11 release, we have fixed several issues and enhancement related to creating survey from existing feature services. Here are the features and enhancement lists we addressed. Please try your regular workflow and any existing feature services in your organization to give a try and provide us your feedback.

1.  Search bar and sort order.
The new searh bar and sort order in the new survey dialog provide a smooth searching experience when querying a large amount of feature services. Please try to use both methods to nagivate to the target feature services in your organization.
![image](https://user-images.githubusercontent.com/29442153/93234941-c93e8f80-f731-11ea-97a2-e770bbcf7a3d.png)
![image](https://user-images.githubusercontent.com/29442153/93235001-d8bdd880-f731-11ea-85d3-ef30a444a2a2.png)

2. Performance improvement to list a large amount of feature services in the organization.
With 3.11 release, when trying to create survey from existing feature services, the time to list a large amount of feature services now has been improved. If you belong to a large organization with many users and feature services, please try to test creating survey from feature service in Connect and let us know if you still see a slow response.
 
3. Addressed BUG-000120582 with publishing a table only feature service.
Prior to 3.11, publish survey with a table only feature service will hang the Connect. We had addressed this issue in 3.11. If you have any table only feature services in your prganization, please test it and let us know if you run into any issue in Connect.
![image](https://user-images.githubusercontent.com/29442153/93239136-3bfe3980-f737-11ea-93c7-fed627870de9.png)

**Comment by Shwujeng** [comment]
Redlands Holistic lab session on 9/16/2020 
- [ ] Alexandra Milanetti
- [ ] Benjamin Wan
- [ ] Carson Smulders
- [ ] Chad Nunemacher
- [ ] Chryse Kruse
- [ ] Francisco Andrade
- [ ] Glen Shepherd
- [ ] Jamie Lambert
- [ ] Jeff Swain
- [ ] Josh Taylor
- [ ] Kylie Donia
- [ ] Louis King Bosso
- [ ] Maggie Samson
- [ ] Manish Patel
- [ ] Ohan Oumoudian
- [ ] Sean Stasio
- [ ] Tarik Ceric
- [ ] Tyler Scuralli

**Comment by J8L** [comment]
When selecting My Surveys as the initial design option, I would like to also see unpublished surveys in the list - and be able to filter these also.

And maybe all surveys in the My Survey Design folder on the computer. I have surveys published with different IDs and different Organizations, though they are all in My Surveys on my computer.

I could use the File option to navigate to the XLSForm, though I then also have to go to the existing survey folder and copy the Media contents (and anything else I need). Also I would prefer to default folder location that opens when selecting this option to be to the My Surveys folder rather than the Application folder. 

Otherwise have an option to create a new survey from the My Surveys folder - and everything is copied to the new survey. This may be the simplest option to implement.

In Connect, when creating a new survey and selection My Surveys, or My Organization, or Feature Service as the source, the icons are all missing, except one, and replaced with the default icon which is flashing. Like its trying to load them but just can't.

![S123beta_Icons](https://user-images.githubusercontent.com/42594789/93543573-428eea00-f99f-11ea-9a8e-3288a0ceb7b4.jpg)

I see this when I first select 'Community' as the source, though after a second or two the correct icons appear.


This is for the Field App (3.11.141 beta) on iOS (from TestFlight) - in the Download Surveys window, the icons on the left are all missing (they can be seen on the main survey page) and the default images are flashing. This is both old surveys and a new survey that I added an icon to.

![DownloadSurveys](https://user-images.githubusercontent.com/42594789/93543586-47ec3480-f99f-11ea-9a74-370b8dd87c1c.png)

**Comment by J8L** [comment]
If I am not signed in, the My surveys, My organization, and the Feature services options are unresponsive - no error message or sign-in prompt. There is an orange sign-in button in the bottom left, though it would be good if these options could be greyed-out until you sign-in.

I have been getting this issue (image below) on 3.10 and with 3.11 beta where there are a few errors when creating the form from an existing feature service. A problem with some content in the xlsx file. Clicking Yes to recover results in Removed Part: Print options.

![XLSForm_Error](https://user-images.githubusercontent.com/42594789/93549799-75d87580-f9ad-11ea-991d-daafc4612d3f.png)


And this error (image below) on the geometry/map and image question. Though I don't get this error for all feature services. I guess guess it depends how the feature is created (if your feature is a /0, /1, etc.)..

/arcgis/rest/services/Emergency_Lines/FeatureServer/0    vs   /arcgis/rest/services/Valve_Sites/FeatureServer 

![XLSFromConversionError](https://user-images.githubusercontent.com/42594789/93549816-7bce5680-f9ad-11ea-8729-a23be4728609.png)
