### ISSUE TITLE
[FEEDBACK] - Quick reference guide page for feature report template.

### ISSUE THREAD

**Issue by Shwujeng** [tedrick/Survey123-Testing#391]
In 3.11 release, the website introduces a new "quick reference" page for each survey to provide sample syntax for all questions in the survey, this is used to replace the previous small table (which missed question types and also sample syntax) in the manage report template dialog on the Data page.

To open the new quick reference page: 
Open the Data page of a survey->Report panel->Manage templates->Quick reference
![image](https://user-images.githubusercontent.com/29442153/93240843-7d8fe400-f739-11ea-8def-f4614cc45ff4.png)
![image](https://user-images.githubusercontent.com/29442153/93240895-8d0f2d00-f739-11ea-8942-ea7de386fbb2.png)

Please use https://survey123beta.arcgis.com/ for this new feature and provide us your feedback on this new dedicated page of quick reference guide of feature report template.

**Comment by Shwujeng** [comment]
Redlands Holistic lab session on 9/16/2020 
- [ ] Alexandra Milanetti
- [ ] Benjamin Wan
- [ ] Carson Smulders
- [ ] Chad Nunemacher
- [ ] Chryse Kruse
- [ ] Francisco Andrade
- [ ] Glen Shepherd
- [ ] Jamie Lambert
- [ ] Jeff Swain
- [ ] Josh Taylor
- [ ] Kylie Donia
- [ ] Louis King Bosso
- [ ] Maggie Samson
- [ ] Manish Patel
- [ ] Ohan Oumoudian
- [ ] Sean Stasio
- [ ] Tarik Ceric
- [ ] Tyler Scuralli

**Comment by amilanetti** [comment]
When clicking the copy button for the mapRotation example syntax and then pasting into a Word Document there is an extra space added before the mapRotation text. However, this doesn't seem to impact generating a report. No syntax errors and the resulting report has the map rotated correctly. 
![MapRotation](https://user-images.githubusercontent.com/43791259/93376314-67f8e800-f827-11ea-8d85-de85bcb43d95.JPG)

When my browser window is maximized on my screen the blue highlighting for which question information is showing does not ever move to highlight the bottom 'Enter your location' section. I think this is because it cannot scroll enough to move that section further up on the page. If I make the browser window smaller then this works correctly. 
![QuestionTypeHighlight](https://user-images.githubusercontent.com/43791259/93376676-ed7c9800-f827-11ea-8c52-9c93cb922c75.JPG)

**Comment by msamsonGIS** [comment]
I really enjoy this feature seems to be working well with my surveys. It makes the process of building a Feature Report template much easier and I think it will get more users working with this functionality. The only issue I was able to notice was with the blue bar on the left side of the page that highlights the question you are on. It will not follow down the page when I scroll because the length of the page is too short. However, clicking on the question on the left side will scroll to the correct section of the document.

![image](https://user-images.githubusercontent.com/71398737/93378227-2453ad80-f82a-11ea-8b2a-7ed555ddd29a.png)
