### ISSUE TITLE
select_one_from_file answers not coming through in feature report

### ISSUE THREAD

**Issue by sarahallerton** [tedrick/Survey123-Testing#393]
I tested generating a feature report from survey data that used the select_one_from_file question type and the data didn't come through using the default template. 

If you download the default template, the field is there but the initial template doesn't contain the field (selected from the File Option drop down on the left hand side). However, when you generate the feature report with the field there, it doesn't pull the data through.

![image](https://user-images.githubusercontent.com/48110084/93424884-09a63500-f90d-11ea-9b34-ffd8e1ab9d26.png)

**Comment by jim-moore** [comment]
As discussed in this morning's stand-up, this is due to the choices not being stored as a domain in the feature layer.

Similar issue with external selects displaying the name instead of the label (see issue no. 50 in the Beijing feature report repo), however in this case neither label or name are showing - the question is blank in the report output.

@tedrick @zhif7782 @marikavertzonis
