### ISSUE TITLE
Bug - Exporting data from Survey123 website to a csv, excel, shapefile, exports incorrect data results

### ISSUE THREAD

**Issue by bethanyw** [tedrick/Survey123-Testing#66]
**Application:** Website

**Device:** _Important for Field App especially_

**Operating System:** Windows 7 Enterprise

**Browser:** Google Chrome

**Error Description:** 

---See the following results submitted to the survey (notice for question named Test 2, for both questions "Choice 2" was submitted)

![2017-10-10_14-17-17](https://user-images.githubusercontent.com/24254787/31402990-c030639a-adc5-11e7-9f8b-6851dea5e2e9.jpg)

----Exporting the data to csv, shapefile, or excel exports the wrong results

![2017-10-10_14-19-56](https://user-images.githubusercontent.com/24254787/31403127-37ac56ea-adc6-11e7-94bf-4969419b7b4d.jpg)

---Exporting to fgdb gives the correct results

**How to reproduce:**

1) Create a survey with a select one question type
2) Fill out the survey with combinations of answers
3) Go to survey123dev.arcgis.com > Data > Export > Choose CSV, Excel, or Shapefile (issue occurs with all of these) > Export the data and open it up
4) Incorrect results shown for select one question type

**Have you tested with another survey?** 

No, issue was reproducible with "select one" question types

**Comment by zhif7782** [comment]
Hi @bethanyw thanks for the feedback. 

However, it's a known limitation and expected behavior currently. When adding a Single Choice/Dropdown question to a survey in the website, after publishing, corresponding coded value domains will be created in the field of feature service layer, where `choice0`, `choice1`, `choice2`... will be the default code to the first, second, third... choice items.

After exporting, code of coded value domain (`choice1` in your case) will be used for CSV, Excel, Shapefile format while name/description of the coded value domain (`Choice 2` in your case) will be used for File Geodatabase format. It's an inherited behavior/known limitation from ArcGIS Online. 

You can work around this by using the new feature described in https://github.com/tedrick/Survey123-Testing/issues/42

**Comment by JohnHasthorpe** [comment]
Known limitation - closing
