### ISSUE TITLE
using web form to enter data "please click here to submit again" does not work

### ISSUE THREAD

**Issue by billwie** [tedrick/Survey123-Testing#86]
**Application:** Survey123qa.arcgis.com - note problem does not exist in Survey123.arcgis.com

**Device:** Windows PC

**Operating System:** Windows 10

**Browser:** Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Error Description:** When using the survey link to enter data after completing entering data and clicking submit click the"please click here to submit again" link. we receive an error: The survey does not exist or is not accessible.

**How to reproduce:** see error description above. we are using Survey123qa against our 10.5.1 portal with SAML authentication using the portalURL querystring.

**Have you tested with another survey?** no but tested with survey123.arcgis.com with no issues.

**Comment by billwie** [comment]
Confirmed under second user. Same Portal 10.5.1 platform

**Comment by tedrick** [comment]
Will attempt to replicate.  @zhif7782

**Comment by zhif7782** [comment]
Cannot reproduce the issue in both:
* 2.5 PROD: https://survey123.arcgis.com?portalUrl=https://ess-enterprise.maps.arcgis.com
* 2.6 QA: https://survey123qa.arcgis.com?portalUrl=https://ess-enterprise.maps.arcgis.com

The "Please click here to submit again" both work as expected. 

Also tested against a 10.5.1 SAML portal https://rpubs120031.ags.esri.com/portal/home/ from http://desktopqa/Masada/public/index.html#release , cannot reproduce the issue too. 
* Note: since the portal is inside Esri network, I created the survey in QA website but publish the survey on a local dev machine (with same code on QA website) and then open the webform in QA website again
![aaa](https://user-images.githubusercontent.com/7665168/35222937-b09cde12-ffba-11e7-92ac-bec8d8659b1a.gif)

@billwie @tedrick is there any other 10.5.1 SAML portal we could use to reproduce the issue?
