### ISSUE TITLE
As Administrator I now see everyone's surveys

### ISSUE THREAD

**Issue by billwie** [tedrick/Survey123-Testing#91]
**Application:** survey123qa.arcgis.com, in survey123.arcgis.com i only see my own surveys

**Device:** Windows PC

**Operating System:** Windows 10

**Browser:** Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Error Description:** not sure if this is by design, but in survey123qa.arcgis.com i see everyones' surveys, not just the ones i authored. survey123.arcgis.com does not behave this way.

**How to reproduce:** we are working against a 10.5.1 SAML Authenticated Portal

**Have you tested with another survey?**

**Comment by sbubka94** [comment]
I have seen this problem occur since the 2.4 release on the website. Occasionally, when I click on the "Sign In" button, it will not actually bring me to the sign in screen, but will bring me to the entire My Surveys library for every ArcGIS Online user. 

![image](https://user-images.githubusercontent.com/22916127/35173204-7584c972-fd1f-11e7-84c8-005ce2e78c75.png)

**Comment by tedrick** [comment]
@billwie , does the "All Surveys/Surveys I own/Surveys shared with me" dropdown in the upper left not work?

**Comment by zhif7782** [comment]
cc @ediyacoo
